# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute product of factors
#'
#' A Rcpp implementation of the factor product algortihm in Koller (2009).
#'
#' @name factor_product
#' @param factors list of arrays representing values of factors, see details.
#' @details Each factor `x` in `factors` must be a numeric vector with length 1
#' or have the following attributes (e.g. an array in R):
#'
#' - x.attr("dim") the cardinality of each variable in `x`
#' - x.attr("dimnames") a named list where the names are the names of the variable in the factor (its scope).
#'
#' @returns an array with the factor product of all factors in `factors`
#' @examples
#'
#' new_factor <- function(data, dim, scope) array(data, dim, setNames(vector("list", length(dim)), scope))
#' x <- new_factor(1:10, c(2, 5), c("a", "b"))
#' y <- new_factor(1:5, 5, c("b"))
#' factor_product(list(x, y))
NULL

rarray <- function(values, dim, dimnames, scope = as.character( c())) {
    .Call(`_SumProductVE_rarray`, values, dim, dimnames, scope)
}

#' @rdname factor_product
#' @export
#'
factor_product <- function(factors) {
    .Call(`_SumProductVE_factor_product`, factors)
}

